version: '3'

services:
  db:
    container_name: northwind_db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 55432:5432
  adminer:
    image: adminer:latest
    ports:
      - 55080:8080
